"""Small reviewed reading lexicon; these are common senses, not an exam word list.

Columns: headword | Chinese meaning in academic/technical prose | literal variants.
Context-specific annotations can override these hints without changing source text.
"""

ENTRIES = """
abstract|抽象的；摘要|abstraction,abstractions
accessible|可访问的；易理解的|accessibility
accumulate|累积|accumulates,accumulated,accumulating
accurate|准确的|accuracy,accurately
adequate|足够的；适当的|adequately
adjacent|相邻的|
aggregate|汇总；聚合|aggregates,aggregation,aggregating
allocate|分配（资源或内存）|allocates,allocated,allocation
alternative|替代方案；另一种选择|alternatives,alternatively
ambiguous|含糊的；有多种解释的|ambiguity
analogous|相似的；类似的|
approximately|大约；近似地|approximate,approximation
arbitrary|任意的；未作特定限制的|arbitrarily
argument|实参；论点（依上下文区分）|arguments
array|数组|arrays
assign|赋值；分配|assigns,assigned,assignment
associated|相关联的|associate,associates,association
assume|假定；认为|assumes,assumed,assuming
attribute|属性；特征|attributes
axis|轴；数组的一个维度|axes
backward compatible|向后兼容的|backwards compatible
benchmark|性能基准；基准测试|benchmarks,benchmarking
bias|偏差；偏置|biased
broadcasting|广播：使不同形状数组参与运算|broadcast
capable|能够……的；有能力的|
categorical|类别型的|
characteristic|特点；特征|characteristics
coefficient|系数|coefficients
coherent|连贯的；一致的|
collapse|折叠；合并|collapses,collapsed
compatible|兼容的；可配合使用的|compatibility
compile|编译；汇编整理|compiles,compiled,compilation
complement|补充；补集|complementary
complexity|复杂度；复杂性|
component|组成部分；组件|components
comprehensive|全面的；详尽的|
compute|计算|computes,computed,computing,computation,computational
concatenate|拼接；连接|concatenates,concatenated,concatenation
concept|概念|concepts,conceptual
concurrent|并发的；同时发生的|concurrency
consecutive|连续的；接连的|
consistent|一致的；保持不变的|consistency,consistently
constant|常量；恒定的|constants
constraint|限制；约束条件|constraints,constrained
construct|构造；创建|constructs,constructed,construction
consume|消耗|consumes,consumed,consumption
container|容器：存放其他对象的结构|containers
contiguous|连续相邻的（如内存空间）|contiguously
convention|惯例；约定|conventions,conventional
convert|转换|converts,converted,conversion
coordinate|坐标|coordinates
correlation|相关关系；相关性|correlated,correlations
correspond|对应；相符合|corresponds,corresponding,correspondence
criterion|标准；判定条件|criteria
crucial|关键的；至关重要的|
cumulative|累积的|
data type|数据类型|data types
decompose|分解|decomposition,decomposed
default|默认值；默认的|defaults
define|定义；明确说明|defines,defined,definition,definitions
demonstrate|演示；说明|demonstrates,demonstrated,demonstration
dependent|依赖的|dependence,dependency,dependencies
deprecated|已弃用的（通常尚未立即移除）|deprecation
derive|推导；获得|derived,derives,derivation
desired|所需的；期望的|
determine|确定；决定|determines,determined
dimension|维度；方面|dimensions,dimensional,dimensionality
disambiguate|消除歧义|disambiguation
discrete|离散的|
distinguish|区分；辨别|distinguishes,distinguished,distinguishing
distribution|分布；发行版本|distributions
diverse|多种多样的|diversity
dtype|数据类型（NumPy 属性）|
efficient|高效的|efficiently,efficiency
element|元素；组成部分|elements
elementwise|逐元素的；对每个元素分别进行的|element-wise
eliminate|消除；去掉|eliminates,eliminated,elimination
emphasize|强调|emphasizes,emphasized,emphasis
enable|使能够；启用|enables,enabled,enabling
encapsulate|封装|encapsulates,encapsulation
encounter|遇到；碰到|encounters,encountered
ensure|确保|ensures,ensured,ensuring
equivalent|等价的；具有同样效果的|equivalence
estimate|估计；估算|estimates,estimated,estimation
estimator|估计器；实现拟合等接口的模型对象|estimators
evaluate|评估；求值|evaluates,evaluated,evaluation
exception|异常；例外|exceptions
exclude|排除；不包括|excludes,excluded,excluding
explicit|明确指定的；显式的|explicitly
exploit|利用（某种特性）|exploits,exploiting
expose|提供访问；公开|exposes,exposed
extend|扩展|extends,extended,extension,extensions
extract|提取|extracts,extracted,extraction
feature|特征；功能|features
finite|有限的|
flexible|灵活的|flexibility
floating point|浮点数；浮点表示|floating-point
fundamental|基本的；根本的|fundamentals
generalize|推广；泛化|generalizes,generalized,generalization
generic|通用的|
heterogeneous|异质的；包含不同类型的|
homogeneous|同质的；类型相同的|
identical|完全相同的|
illustrate|说明；举例展示|illustrates,illustrated,illustration
immutable|不可变的|
implement|实现；实施|implements,implemented,implementation
implicit|隐含的；隐式的|implicitly
imply|意味着；暗示|implies,implied
in contrast|相比之下；与此形成对照|
in place|原地进行（直接修改原对象）|in-place
in particular|尤其；特别是|
in terms of|就……而言；以……来衡量|
independent|独立的|independence,independently
index|索引|indices,indexes,indexing
indicate|表明；指出|indicates,indicated,indication
infer|推断|inferred,inference
inherit|继承|inherits,inherited,inheritance
initialize|初始化|initializes,initialized,initialization
instance|实例；具体对象|instances
integer|整数|integers
intermediate|中间的；中级的|
interpret|解释；理解|interpreted,interpreter,interpretation
interval|区间；间隔|intervals
intrinsic|固有的；内在的|
invoke|调用|invokes,invoked,invocation
iterate|迭代；逐项处理|iterates,iteration,iterations,iterating
iterator|迭代器|iterators
label|标签；标注|labels,labelled,labeled
likelihood|可能性；似然|
linear|线性的|linearly
logical|逻辑的|
maintain|保持；维护|maintains,maintained,maintenance
manipulate|操作；处理|manipulates,manipulation
matrix|矩阵|matrices
mechanism|机制；作用方式|mechanisms
metric|衡量指标|metrics
modify|修改|modifies,modified,modification
multidimensional|多维的|
mutable|可变的；可修改的|
ndarray|N 维数组（NumPy 的数组对象）|ndarrays
nevertheless|尽管如此；然而|
notation|记号；表示法|
numerical|数值的|numerically
obtain|获得|obtains,obtained
offset|偏移量|offsets
operand|操作数；运算对象|operands
optimal|最优的|optimize,optimized,optimization
optional|可选的；非必需的|
otherwise|否则；在其他情况下|
overfit|过拟合|overfitting,overfitted
parameter|参数（函数定义或模型中的变量）|parameters
performance|性能；表现|
persist|持久保存；持续存在|persists,persistence
pipeline|流水线；一系列串联的处理步骤|pipelines
precision|精度；精确率（依上下文区分）|
predict|预测|predicts,prediction,predictions,predicted
prefix|前缀|prefixes
preserve|保留；保持|preserves,preserved
primarily|主要地|
prior|先前的；先验的|
probability|概率；可能性|probabilities
proportion|比例|proportions,proportional
provided that|只要；条件是|
rectangular|矩形的；各行长度一致的|
recursive|递归的|recursion,recursively
refer|指代；提及|refers,referred,referring
regression|回归|
regularization|正则化：约束模型以减少过拟合|
relevant|相关的；切题的|
represent|表示；代表|represents,represented,representation
require|需要；要求|requires,required,requirement,requirements
reshape|改变数组形状|reshapes,reshaped,reshaping
residual|残差；剩余的|residuals
respectively|分别地；按前述顺序对应地|
restrict|限制|restricts,restricted,restriction,restrictions
retrieve|取回；检索；读取|retrieves,retrieved,retrieval
robust|稳健的；不易受干扰的|robustness
scalar|标量|scalars
sequence|序列；次序|sequences,sequential
shape|形状；数组各维度的大小|shapes
significant|显著的；重要的|significantly,significance
similarity|相似性|similarities
simultaneous|同时发生的|simultaneously
slice|切片；选取一段元素|slices,slicing
specify|指定；明确说明|specifies,specified,specifying
stable|稳定的|stability
standard deviation|标准差|
subsequent|随后发生的；后续的|subsequently
subset|子集；一部分|subsets
substantial|大量的；实质性的|substantially
supervised|有监督的（学习）|
sufficient|足够的|sufficiently
syntax|语法；代码的书写规则|
tensor|张量|tensors
terminate|终止|terminates,terminated,termination
therefore|因此|
threshold|阈值；临界值|thresholds
transform|转换；变换|transforms,transformed,transformation
transpose|转置|transposed,transposing
tuple|元组|tuples
underlying|底层的；背后的|
uniform|均匀的；一致的|uniformly
unique|唯一的；互不相同的|
universal|通用的；普遍的|
unsupervised|无监督的（学习）|
valid|有效的；合法的|validity,validate,validation
variance|方差|
vector|向量|vectors
view|视图；查看（依上下文区分）|views
whereas|而；然而（引出对比）|
widespread|广泛使用的；普遍的|
within|在……范围内|
yield|产生；返回（生成器中的值）|yields,yielding
""".strip()

# Derived forms with a different grammatical role need their own hint.
ENTRIES += """
accuracy|准确性|
accurately|准确地|
abstraction|抽象化；抽象概念|abstractions
accessibility|可访问性；易用性|
alternatively|作为另一种选择；或者|
approximate|近似的；估算|
approximation|近似值；估算|
arbitrarily|任意地|
association|关联；联系|
computational|计算的；与计算有关的|
conceptual|概念上的|
conventional|惯常的；约定俗成的|
consistently|始终如一地|
dimensional|维的；与维度有关的|
explicitly|明确地；显式地|
implicitly|隐含地；隐式地|
independently|独立地|
interpreter|解释器|interpreters
definition|定义|definitions
efficiently|高效地|
efficiency|效率|
linearly|线性地|
numerically|在数值上；用数值方式|
open source|开源的；开放源代码的|open-source
optimize|优化|optimizes,optimized,optimizing
optimization|优化|
proportional|成比例的|
recursively|递归地|
sequential|依次进行的；顺序的|
significance|重要性；显著性|
significantly|显著地；大幅地|
simultaneously|同时地|
subsequently|随后；后来|
substantially|大幅地；实质上|
invocation|调用|
compatibility|兼容性|
dimensionality|维数；维度数量|
restriction|限制；约束|restrictions
correspondence|对应关系|
consumption|消耗量|
uniformly|均匀地；一致地|
validity|有效性|
validate|验证|validates,validated,validating
validation|验证|
"""
