"""baseline schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-18 20:47:08.227195

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corpora',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source_path', sa.String(), nullable=False),
    sa.Column('source_hash', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('encoding', sa.String(), nullable=True),
    sa.Column('chapter_count', sa.Integer(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('corpora', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_corpora_source_hash'), ['source_hash'], unique=False)

    op.create_table('vocabulary_marks',
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('payload', sa.Text(), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('word')
    )
    with op.batch_alter_table('vocabulary_marks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vocabulary_marks_status'), ['status'], unique=False)

    op.create_table('vocabulary_reviews',
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('box', sa.Integer(), server_default='1', nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('seen', sa.Integer(), server_default='0', nullable=False),
    sa.Column('lapses', sa.Integer(), server_default='0', nullable=False),
    sa.Column('payload', sa.Text(), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('word')
    )
    with op.batch_alter_table('vocabulary_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vocabulary_reviews_due_at'), ['due_at'], unique=False)

    op.create_table('writing_evaluations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('writing_evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_writing_evaluations_task_type'), ['task_type'], unique=False)

    op.create_table('corpus_approvals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('corpus_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['corpus_id'], ['corpora.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('corpus_approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_corpus_approvals_corpus_id'), ['corpus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_corpus_approvals_status'), ['status'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('corpus_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['corpus_id'], ['corpora.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_corpus_id'), ['corpus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('source_chapters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('corpus_id', sa.String(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['corpus_id'], ['corpora.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_chapters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_chapters_corpus_id'), ['corpus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_chapters_ordinal'), ['ordinal'], unique=False)

    op.create_table('generation_units',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('corpus_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['corpus_id'], ['corpora.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generation_units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generation_units_corpus_id'), ['corpus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_units_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_units_ordinal'), ['ordinal'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_units_status'), ['status'], unique=False)

    op.create_table('practice_attempts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('unit_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['generation_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('practice_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_practice_attempts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_attempts_unit_id'), ['unit_id'], unique=False)

    op.create_table('review_samples',
    sa.Column('unit_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('payload', sa.Text(), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['generation_units.id'], ),
    sa.PrimaryKeyConstraint('unit_id')
    )
    with op.batch_alter_table('review_samples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_samples_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_samples_status'), ['status'], unique=False)

    op.create_table('stage_attempts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('unit_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('cache_key', sa.String(), nullable=True),
    sa.Column('payload', sa.Text(), server_default='{}', nullable=False),
    sa.Column('artifact_path', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['generation_units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id', 'stage', 'attempt', name='uq_stage_attempt_identity')
    )
    with op.batch_alter_table('stage_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stage_attempts_cache_key'), ['cache_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_stage_attempts_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stage_attempts_stage'), ['stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_stage_attempts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_stage_attempts_unit_id'), ['unit_id'], unique=False)
        batch_op.create_index('uq_stage_attempt_completed_cache_key', ['cache_key'], unique=True, sqlite_where=sa.text("status = 'completed'"))

    op.create_table('usage_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unit_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['generation_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_records_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_records_stage'), ['stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_records_unit_id'), ['unit_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_records_unit_id'))
        batch_op.drop_index(batch_op.f('ix_usage_records_stage'))
        batch_op.drop_index(batch_op.f('ix_usage_records_job_id'))

    op.drop_table('usage_records')
    with op.batch_alter_table('stage_attempts', schema=None) as batch_op:
        batch_op.drop_index('uq_stage_attempt_completed_cache_key', sqlite_where=sa.text("status = 'completed'"))
        batch_op.drop_index(batch_op.f('ix_stage_attempts_unit_id'))
        batch_op.drop_index(batch_op.f('ix_stage_attempts_status'))
        batch_op.drop_index(batch_op.f('ix_stage_attempts_stage'))
        batch_op.drop_index(batch_op.f('ix_stage_attempts_job_id'))
        batch_op.drop_index(batch_op.f('ix_stage_attempts_cache_key'))

    op.drop_table('stage_attempts')
    with op.batch_alter_table('review_samples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_samples_status'))
        batch_op.drop_index(batch_op.f('ix_review_samples_job_id'))

    op.drop_table('review_samples')
    with op.batch_alter_table('practice_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_practice_attempts_unit_id'))
        batch_op.drop_index(batch_op.f('ix_practice_attempts_status'))

    op.drop_table('practice_attempts')
    with op.batch_alter_table('generation_units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generation_units_status'))
        batch_op.drop_index(batch_op.f('ix_generation_units_ordinal'))
        batch_op.drop_index(batch_op.f('ix_generation_units_job_id'))
        batch_op.drop_index(batch_op.f('ix_generation_units_corpus_id'))

    op.drop_table('generation_units')
    with op.batch_alter_table('source_chapters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_chapters_ordinal'))
        batch_op.drop_index(batch_op.f('ix_source_chapters_corpus_id'))

    op.drop_table('source_chapters')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_corpus_id'))

    op.drop_table('jobs')
    with op.batch_alter_table('corpus_approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corpus_approvals_status'))
        batch_op.drop_index(batch_op.f('ix_corpus_approvals_corpus_id'))

    op.drop_table('corpus_approvals')
    with op.batch_alter_table('writing_evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_writing_evaluations_task_type'))

    op.drop_table('writing_evaluations')
    with op.batch_alter_table('vocabulary_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vocabulary_reviews_due_at'))

    op.drop_table('vocabulary_reviews')
    with op.batch_alter_table('vocabulary_marks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vocabulary_marks_status'))

    op.drop_table('vocabulary_marks')
    with op.batch_alter_table('corpora', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corpora_source_hash'))

    op.drop_table('corpora')
    # ### end Alembic commands ###
