"""job queue leases and idempotency

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-20 03:29:04.442074

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.String(), server_default='reading_generation', nullable=False))
        batch_op.add_column(sa.Column('worker_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('attempts', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('error_code', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('idempotency_key', sa.String(), nullable=True))
        batch_op.create_index('ix_jobs_status_created_at', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_worker_id'), ['worker_id'], unique=False)
        batch_op.create_index('uq_jobs_idempotency_key', ['idempotency_key'], unique=True, sqlite_where=sa.text('idempotency_key IS NOT NULL'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('uq_jobs_idempotency_key', sqlite_where=sa.text('idempotency_key IS NOT NULL'))
        batch_op.drop_index(batch_op.f('ix_jobs_worker_id'))
        batch_op.drop_index('ix_jobs_status_created_at')
        batch_op.drop_column('idempotency_key')
        batch_op.drop_column('error_code')
        batch_op.drop_column('attempts')
        batch_op.drop_column('heartbeat_at')
        batch_op.drop_column('lease_expires_at')
        batch_op.drop_column('worker_id')
        batch_op.drop_column('kind')

    # ### end Alembic commands ###
