"""web sessions and persistent rate limiting

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-20 04:09:53.905674

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limit_hits',
    sa.Column('bucket', sa.String(), nullable=False),
    sa.Column('window_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hits', sa.Integer(), server_default='0', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('bucket', 'window_started_at')
    )
    with op.batch_alter_table('rate_limit_hits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rate_limit_hits_expires_at'), ['expires_at'], unique=False)

    op.create_table('web_sessions',
    sa.Column('id_hash', sa.String(), nullable=False),
    sa.Column('csrf_token', sa.String(), nullable=False),
    sa.Column('authenticated', sa.Integer(), server_default='0', nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('client_ip', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('idle_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('absolute_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('web_sessions')
    with op.batch_alter_table('rate_limit_hits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rate_limit_hits_expires_at'))

    op.drop_table('rate_limit_hits')
    # ### end Alembic commands ###
